#!/usr/bin/env python3
# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
"""Embed the release timestamp, independently of Chromium's binary version."""
import argparse
import datetime
from pathlib import Path


def read_version(path):
    value = path.read_text(encoding='utf-8').strip()
    if len(value) != 14 or not value.isascii() or not value.isdigit():
        raise ValueError('version.txt must contain YYYYMMDDHHMMSS UTC')
    parsed = datetime.datetime.strptime(value, '%Y%m%d%H%M%S')
    if parsed.year < 2020 or parsed.strftime('%Y%m%d%H%M%S') != value:
        raise ValueError('Invalid release timestamp')
    return value


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--input', type=Path, required=True)
    parser.add_argument('--output', type=Path, required=True)
    args = parser.parse_args()
    version = read_version(args.input)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        '// Generated by generate_joao_version.py.\n'
        '#ifndef CHROME_BROWSER_UI_WEBUI_HELP_JOAO_RELEASE_VERSION_H_\n'
        '#define CHROME_BROWSER_UI_WEBUI_HELP_JOAO_RELEASE_VERSION_H_\n'
        f'inline constexpr char kJoaoReleaseVersion[] = "{version}";\n'
        '#endif\n', encoding='utf-8')


if __name__ == '__main__':
    main()
